spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd?serverTimezone=GMT-3
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host : smtp.gmail.com
    port: 587
    username: proyectosoftwarecontacto@gmail.com
    password: proyectoN12
    properties:
      mail:
        smtp:
          starttls :
            enable : true
          auth : true
